.test:
  tags:
  - flarenetwork
  image: node:16
  variables:
    NODE_ENV: development
  before_script:
  - yarn install --frozen-lockfile



test-coverage:
  extends: .test
  script: [ "yarn run test:coverage" ]
  rules:
  - when: on_success
