/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface StateConnectorMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): StateConnectorMock;
  clone(): StateConnectorMock;
  methods: {
    BUFFER_WINDOW(): NonPayableTransactionObject<string>;

    TOTAL_STORED_PROOFS(): NonPayableTransactionObject<string>;

    merkleRoots(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    setMerkleRoot(
      _stateConnectorRound: number | string | BN,
      _merkleRoot: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
