/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface HashTestContract extends Truffle.Contract<HashTestInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<HashTestInstance>;
}

type AllEvents = never;

export interface HashTestInstance extends Truffle.ContractInstance {
  testBlockHeightProof(
    typ: number | BN | string,
    chainId: number | BN | string,
    blockNumber: number | BN | string,
    txId: string,
    sourceAddress: string,
    spent: number | BN | string,
    hashToProve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  testDecreaseBalanceProof(
    typ: number | BN | string,
    chainId: number | BN | string,
    blockNumber: number | BN | string,
    txId: string,
    sourceAddress: string,
    spent: number | BN | string,
    hashToProve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  testPaymentProof(
    typ: number | BN | string,
    chainId: number | BN | string,
    blockNumber: number | BN | string,
    blockTimestamp: number | BN | string,
    txId: string,
    utxo: number | BN | string,
    sourceAddress: string,
    destinationAddress: string,
    paymentReference: number | BN | string,
    spent: number | BN | string,
    delivered: number | BN | string,
    isFromOne: boolean,
    status: number | BN | string,
    hashToProve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  verifyMerkleProof(
    proof: string[],
    merkleRoot: string,
    leaf: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    testBlockHeightProof(
      typ: number | BN | string,
      chainId: number | BN | string,
      blockNumber: number | BN | string,
      txId: string,
      sourceAddress: string,
      spent: number | BN | string,
      hashToProve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    testDecreaseBalanceProof(
      typ: number | BN | string,
      chainId: number | BN | string,
      blockNumber: number | BN | string,
      txId: string,
      sourceAddress: string,
      spent: number | BN | string,
      hashToProve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    testPaymentProof(
      typ: number | BN | string,
      chainId: number | BN | string,
      blockNumber: number | BN | string,
      blockTimestamp: number | BN | string,
      txId: string,
      utxo: number | BN | string,
      sourceAddress: string,
      destinationAddress: string,
      paymentReference: number | BN | string,
      spent: number | BN | string,
      delivered: number | BN | string,
      isFromOne: boolean,
      status: number | BN | string,
      hashToProve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    verifyMerkleProof(
      proof: string[],
      merkleRoot: string,
      leaf: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
