/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface HashTestContract extends Truffle.Contract<HashTestInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<HashTestInstance>;
}

type AllEvents = never;

export interface HashTestInstance extends Truffle.ContractInstance {
  verifyMerkleProof(
    proof: string[],
    merkleRoot: string,
    leaf: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    verifyMerkleProof(
      proof: string[],
      merkleRoot: string,
      leaf: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
