/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AttestationClientMockContract } from "./AttestationClientMock";
import { IAttestationClientContract } from "./IAttestationClient";
import { StateConnectorContract } from "./StateConnector";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AttestationClientMock"): AttestationClientMockContract;
      require(name: "IAttestationClient"): IAttestationClientContract;
      require(name: "StateConnector"): StateConnectorContract;
    }
  }
}

export {
  AttestationClientMockContract,
  AttestationClientMockInstance,
} from "./AttestationClientMock";
export {
  IAttestationClientContract,
  IAttestationClientInstance,
} from "./IAttestationClient";
export {
  StateConnectorContract,
  StateConnectorInstance,
} from "./StateConnector";
