/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { StateConnectorContract } from "./StateConnector";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "StateConnector"): StateConnectorContract;
    }
  }
}

export {
  StateConnectorContract,
  StateConnectorInstance,
} from "./StateConnector";
